package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;
import java.awt.event.*;

public class ABMDialog extends JDialog {
    public enum Opcion {
        CREAR, MODIFICAR, BAJA, REACTIVAR, VOLVER
    }

    private JPanel contentPane;
    private JLabel labelTitulo;
    private JButton botonVolver;
    private JButton botonReactivar;
    private JButton botonDarDeBaja;
    private JButton botonModificar;
    private JButton botonCrear;

    private Opcion opcion = Opcion.VOLVER;

    public ABMDialog(Window owner, String tituloVentana, String tituloPantalla) {
        super(owner, tituloVentana, ModalityType.APPLICATION_MODAL);
        $$$setupUI$$$();
        setContentPane(contentPane);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        if (labelTitulo != null) {
            labelTitulo.setText(tituloPantalla);
        }

        if (botonCrear != null) botonCrear.addActionListener(e -> elegir(Opcion.CREAR));
        if (botonModificar != null) botonModificar.addActionListener(e -> elegir(Opcion.MODIFICAR));
        if (botonDarDeBaja != null) botonDarDeBaja.addActionListener(e -> elegir(Opcion.BAJA));
        if (botonReactivar != null) botonReactivar.addActionListener(e -> elegir(Opcion.REACTIVAR));
        if (botonVolver != null) botonVolver.addActionListener(e -> elegir(Opcion.VOLVER));

        // X
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                elegir(Opcion.VOLVER);
            }
        });

        // ESC = volver
        contentPane.registerKeyboardAction(
                e -> elegir(Opcion.VOLVER),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
        );

        pack();
        setLocationRelativeTo(owner);
    }

    private void elegir(Opcion op) {
        opcion = op;
        dispose();
    }

    public Opcion showDialog() {
        setVisible(true);
        return opcion;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setBackground(new Color(-14865084));
        contentPane.setForeground(new Color(-15920351));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-14865084));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(60, 60), null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 26, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-988200));
        label1.setText("Label");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-14865084));
        contentPane.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(-1, 35), null, 0, false));
        botonReactivar = new JButton();
        botonReactivar.setBackground(new Color(-15920351));
        botonReactivar.setForeground(new Color(-15920351));
        botonReactivar.setText("Reactivar libro");
        panel2.add(botonReactivar, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
        botonVolver = new JButton();
        botonVolver.setBackground(new Color(-15920351));
        botonVolver.setForeground(new Color(-1217958));
        botonVolver.setText("Volver");
        panel2.add(botonVolver, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
        botonDarDeBaja = new JButton();
        botonDarDeBaja.setBackground(new Color(-15920351));
        botonDarDeBaja.setForeground(new Color(-15920351));
        botonDarDeBaja.setText("Dar de baja");
        panel2.add(botonDarDeBaja, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
        botonModificar = new JButton();
        botonModificar.setBackground(new Color(-15920351));
        botonModificar.setForeground(new Color(-15920351));
        botonModificar.setText("Modificar libro");
        panel2.add(botonModificar, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
        botonCrear = new JButton();
        botonCrear.setBackground(new Color(-15920351));
        botonCrear.setForeground(new Color(-15920351));
        botonCrear.setText("Crear libro");
        panel2.add(botonCrear, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
