package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import domain.ResultadoMenuCajero;
import domain.Usuario;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.*;
import java.util.Locale;

public class MenuCajeroDialog extends JDialog {
    private JPanel contentPane;
    private JButton botonConsultarPrecio;
    private JButton botonBuscarLibros;
    private JButton botonVerStock;
    private JButton botonRegistrarVenta;
    private JButton botonCerrarSesion;
    private JButton botonSalir;
    private JLabel textoBienvenida;
    private JLabel textoSeleccion;

    private ResultadoMenuCajero resultado = ResultadoMenuCajero.CERRADO_VENTANA;

    public MenuCajeroDialog(Window owner, Usuario usuario) {
        super(owner, "Librería Yenny — Menú Cajero", ModalityType.APPLICATION_MODAL);
        setContentPane(contentPane);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        if (textoBienvenida != null) textoBienvenida.setText("Bienvenido/a " + usuario.getNombre());
        if (textoSeleccion != null) textoSeleccion.setText("Seleccione una opción");

        if (botonRegistrarVenta != null)
            botonRegistrarVenta.addActionListener(e -> elegir(ResultadoMenuCajero.REGISTRAR_VENTA));
        if (botonConsultarPrecio != null)
            botonConsultarPrecio.addActionListener(e -> elegir(ResultadoMenuCajero.CONSULTAR_PRECIO));
        if (botonBuscarLibros != null)
            botonBuscarLibros.addActionListener(e -> elegir(ResultadoMenuCajero.BUSCAR_LIBRO));
        if (botonVerStock != null) botonVerStock.addActionListener(e -> elegir(ResultadoMenuCajero.VER_STOCK));
        if (botonCerrarSesion != null)
            botonCerrarSesion.addActionListener(e -> elegir(ResultadoMenuCajero.CERRAR_SESION));
        if (botonSalir != null) botonSalir.addActionListener(e -> elegir(ResultadoMenuCajero.SALIR_SISTEMA));

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                elegir(ResultadoMenuCajero.CERRADO_VENTANA);
            }
        });
        contentPane.registerKeyboardAction(e -> elegir(ResultadoMenuCajero.CERRADO_VENTANA),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        pack();
        setLocationRelativeTo(owner);
    }

    private void elegir(ResultadoMenuCajero r) {
        resultado = r;
        dispose();
    }

    public ResultadoMenuCajero showDialog() {
        setVisible(true);
        return resultado;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 1, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setBackground(new Color(-14865084));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-14865084));
        contentPane.add(panel1, new GridConstraints(0, 0, 4, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(600, 225), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-14865084));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        textoBienvenida = new JLabel();
        textoBienvenida.setBackground(new Color(-988200));
        Font textoBienvenidaFont = this.$$$getFont$$$("Lucida Grande", Font.BOLD, 28, textoBienvenida.getFont());
        if (textoBienvenidaFont != null) textoBienvenida.setFont(textoBienvenidaFont);
        textoBienvenida.setForeground(new Color(-988200));
        textoBienvenida.setHorizontalAlignment(0);
        textoBienvenida.setHorizontalTextPosition(0);
        textoBienvenida.setRequestFocusEnabled(false);
        textoBienvenida.setText("Bienvenido nombre");
        panel2.add(textoBienvenida, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        textoSeleccion = new JLabel();
        textoSeleccion.setForeground(new Color(-988200));
        textoSeleccion.setText("Seleccione una de las siguientes opciones");
        panel2.add(textoSeleccion, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, false, true));
        panel3.setBackground(new Color(-14865084));
        panel1.add(panel3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, new Dimension(-1, 50), null, 0, false));
        botonCerrarSesion = new JButton();
        botonCerrarSesion.setBackground(new Color(-16579837));
        Font botonCerrarSesionFont = this.$$$getFont$$$(null, -1, 16, botonCerrarSesion.getFont());
        if (botonCerrarSesionFont != null) botonCerrarSesion.setFont(botonCerrarSesionFont);
        botonCerrarSesion.setForeground(new Color(-1217958));
        botonCerrarSesion.setIcon(new ImageIcon(getClass().getResource("/resources/icons/logout2.png")));
        botonCerrarSesion.setText("Cerrar sesión");
        panel3.add(botonCerrarSesion, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
        botonSalir = new JButton();
        botonSalir.setBackground(new Color(-16579837));
        Font botonSalirFont = this.$$$getFont$$$(null, -1, 16, botonSalir.getFont());
        if (botonSalirFont != null) botonSalir.setFont(botonSalirFont);
        botonSalir.setForeground(new Color(-1217958));
        botonSalir.setIcon(new ImageIcon(getClass().getResource("/resources/icons/cancel-icon.png")));
        botonSalir.setText("Salir del sistema");
        panel3.add(botonSalir, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
        final JSeparator separator1 = new JSeparator();
        separator1.setAutoscrolls(false);
        separator1.setFocusable(true);
        panel1.add(separator1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel4.setBackground(new Color(-14865084));
        panel1.add(panel4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, new Dimension(-1, 50), null, 0, false));
        botonBuscarLibros = new JButton();
        botonBuscarLibros.setAutoscrolls(true);
        botonBuscarLibros.setBackground(new Color(-988200));
        botonBuscarLibros.setFocusable(false);
        Font botonBuscarLibrosFont = this.$$$getFont$$$(null, -1, 20, botonBuscarLibros.getFont());
        if (botonBuscarLibrosFont != null) botonBuscarLibros.setFont(botonBuscarLibrosFont);
        botonBuscarLibros.setForeground(new Color(-15920351));
        botonBuscarLibros.setIcon(new ImageIcon(getClass().getResource("/resources/icons/libro.png")));
        botonBuscarLibros.setText("Buscar libros");
        panel4.add(botonBuscarLibros, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
        botonVerStock = new JButton();
        botonVerStock.setBackground(new Color(-15920351));
        Font botonVerStockFont = this.$$$getFont$$$(null, -1, 16, botonVerStock.getFont());
        if (botonVerStockFont != null) botonVerStock.setFont(botonVerStockFont);
        botonVerStock.setForeground(new Color(-15920351));
        botonVerStock.setIcon(new ImageIcon(getClass().getResource("/resources/icons/list.png")));
        botonVerStock.setText("Ver stock");
        panel4.add(botonVerStock, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
        botonRegistrarVenta = new JButton();
        botonRegistrarVenta.setBackground(new Color(-15920351));
        Font botonRegistrarVentaFont = this.$$$getFont$$$(null, -1, 16, botonRegistrarVenta.getFont());
        if (botonRegistrarVentaFont != null) botonRegistrarVenta.setFont(botonRegistrarVentaFont);
        botonRegistrarVenta.setForeground(new Color(-15920351));
        botonRegistrarVenta.setIcon(new ImageIcon(getClass().getResource("/resources/icons/journal.png")));
        botonRegistrarVenta.setText("Registrar venta");
        panel4.add(botonRegistrarVenta, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
        botonConsultarPrecio = new JButton();
        botonConsultarPrecio.setBackground(new Color(-15920351));
        botonConsultarPrecio.setForeground(new Color(-15920351));
        botonConsultarPrecio.setIcon(new ImageIcon(getClass().getResource("/resources/icons/money.png")));
        botonConsultarPrecio.setText("Consultar precio");
        panel4.add(botonConsultarPrecio, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 45), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
