package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import domain.StockResumen;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.*;
import java.util.Locale;

public class StockDialog extends JDialog {
    private JPanel contentPane;
    private JButton buttonConfirm;
    private JTable tablaStock;
    private JButton buttonCancel;

    public StockDialog(Window owner, int sucursalId, java.util.List<StockResumen> filas) {
        super(owner, "Stock — Sucursal " + sucursalId, ModalityType.APPLICATION_MODAL);
        setContentPane(contentPane);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        contentPane.setPreferredSize(new Dimension(760, 440));

        Container parent = tablaStock.getParent();
        boolean yaEnScroll = (parent instanceof JViewport) || (parent instanceof JScrollPane);
        if (!yaEnScroll) {
            JScrollPane sp = new JScrollPane(tablaStock);
            if (parent != null) {
                parent.removeAll();
                if (!(parent.getLayout() instanceof BorderLayout)) parent.setLayout(new BorderLayout());
                parent.add(sp, BorderLayout.CENTER);
                parent.validate();
            }
        }
        // ------------------------------------------------------------------------------
        tablaStock.setModel(new StockTableModel(filas));
        tablaStock.setAutoCreateRowSorter(true);
        tablaStock.setFillsViewportHeight(true);
        tablaStock.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tablaStock.getColumnModel().getColumn(0).setPreferredWidth(360);
        tablaStock.getColumnModel().getColumn(1).setPreferredWidth(90);
        tablaStock.getColumnModel().getColumn(2).setPreferredWidth(90);

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable t, Object v, boolean sel, boolean foc, int row, int col) {
                Component c = super.getTableCellRendererComponent(t, v, sel, foc, row, col);
                int mr = t.convertRowIndexToModel(row);
                int cant = (Integer) t.getModel().getValueAt(mr, 1);
                int umb = (Integer) t.getModel().getValueAt(mr, 2);
                if (!sel) c.setForeground(cant <= umb ? new Color(170, 0, 0) : UIManager.getColor("Table.foreground"));
                return c;
            }
        };
        tablaStock.setDefaultRenderer(Object.class, renderer);
        tablaStock.setDefaultRenderer(Integer.class, renderer);

        if (buttonConfirm != null) {
            buttonConfirm.addActionListener(e -> dispose());
            getRootPane().setDefaultButton(buttonConfirm);
        }
        if (buttonCancel != null) {
            buttonCancel.setText("Cerrar");
            buttonCancel.addActionListener(e -> dispose());
        }

        contentPane.registerKeyboardAction(
                e -> dispose(),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
        );

        pack();
        setLocationRelativeTo(owner);
    }


    private void onOK() {
        // add your code here
        dispose();
    }

    private void onCancel() {
        // add your code here if necessary
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setBackground(new Color(-14865084));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-14865084));
        contentPane.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, new Dimension(-1, 50), null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-14865084));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonConfirm = new JButton();
        buttonConfirm.setBackground(new Color(-988200));
        buttonConfirm.setForeground(new Color(-15920351));
        buttonConfirm.setIcon(new ImageIcon(getClass().getResource("/resources/icons/confirm.png")));
        buttonConfirm.setText("OK");
        panel2.add(buttonConfirm, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setBackground(new Color(-14865084));
        contentPane.add(panel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tablaStock = new JTable();
        tablaStock.setBackground(new Color(-14865084));
        tablaStock.setForeground(new Color(-988200));
        tablaStock.setGridColor(new Color(-3356196));
        tablaStock.setSelectionForeground(new Color(-3356196));
        panel3.add(tablaStock, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


}
