package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import domain.StockResumen;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.*;
import java.util.Locale;

public class StockDialog extends JDialog {
    private JPanel contentPane;
    private JButton buttonConfirm;
    private JTable tablaStock;
    private JButton buttonCancel;

    public StockDialog(Window owner, int sucursalId, java.util.List<StockResumen> filas) {
        super(owner, "Stock — Sucursal " + sucursalId, ModalityType.APPLICATION_MODAL);
        setContentPane(contentPane);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        contentPane.setPreferredSize(new Dimension(760, 440));

        Container parent = tablaStock.getParent();
        boolean yaEnScroll = (parent instanceof JViewport) || (parent instanceof JScrollPane);
        if (!yaEnScroll) {
            JScrollPane sp = new JScrollPane(tablaStock);
            if (parent != null) {
                parent.removeAll();
                if (!(parent.getLayout() instanceof BorderLayout)) parent.setLayout(new BorderLayout());
                parent.add(sp, BorderLayout.CENTER);
                parent.validate();
            }
        }
        // ------------------------------------------------------------------------------
        tablaStock.setModel(new StockTableModel(filas));
        tablaStock.setAutoCreateRowSorter(true);
        tablaStock.setFillsViewportHeight(true);
        tablaStock.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tablaStock.getColumnModel().getColumn(0).setPreferredWidth(360);
        tablaStock.getColumnModel().getColumn(1).setPreferredWidth(90);
        tablaStock.getColumnModel().getColumn(2).setPreferredWidth(90);

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable t, Object v, boolean sel, boolean foc, int row, int col) {
                Component c = super.getTableCellRendererComponent(t, v, sel, foc, row, col);
                int mr = t.convertRowIndexToModel(row);
                int cant = (Integer) t.getModel().getValueAt(mr, 1);
                int umb = (Integer) t.getModel().getValueAt(mr, 2);
                return c;
            }
        };

        tablaStock.setDefaultRenderer(Object.class, renderer);
        tablaStock.setDefaultRenderer(Integer.class, renderer);

        DefaultTableCellRenderer cell = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable t, Object v, boolean sel, boolean foc, int row, int col) {
                Component c = super.getTableCellRendererComponent(t, v, sel, foc, row, col);
                ((JLabel) c).setBorder(new EmptyBorder(0, 8, 0, 8));
                ((JLabel) c).setHorizontalAlignment((col == 1 || col == 2) ? SwingConstants.CENTER : SwingConstants.LEFT);
                return c;
            }
        };
        tablaStock.setDefaultRenderer(Object.class, cell);
        tablaStock.setDefaultRenderer(Integer.class, cell);

        JTableHeader h = tablaStock.getTableHeader();
        h.setFont(h.getFont().deriveFont(Font.BOLD, 16f));
        h.setPreferredSize(new Dimension(h.getPreferredSize().width, 28));

        if (buttonConfirm != null) {
            buttonConfirm.addActionListener(e -> dispose());
        }
        if (buttonCancel != null) {
            buttonCancel.setText("Cerrar");
            buttonCancel.addActionListener(e -> dispose());
        }

        getRootPane().registerKeyboardAction(
                e -> {
                    if (buttonConfirm != null) buttonConfirm.doClick();
                },
                KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW
        );

        pack();
        setLocationRelativeTo(owner);
    }


    private void onOK() {
        // add your code here
        dispose();
    }

    private void onCancel() {
        // add your code here if necessary
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setBackground(new Color(-14865084));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-14865084));
        contentPane.add(panel1, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(900, 400), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-14865084));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, new Dimension(-1, 50), null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setBackground(new Color(-14865084));
        panel2.add(panel3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonConfirm = new JButton();
        buttonConfirm.setBackground(new Color(-919571));
        buttonConfirm.setBorderPainted(true);
        Font buttonConfirmFont = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 20, buttonConfirm.getFont());
        if (buttonConfirmFont != null) buttonConfirm.setFont(buttonConfirmFont);
        buttonConfirm.setForeground(new Color(-15920351));
        buttonConfirm.setIcon(new ImageIcon(getClass().getResource("/resources/icons/ok.png")));
        buttonConfirm.setText("OK");
        panel3.add(buttonConfirm, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel3.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel4.setBackground(new Color(-14865084));
        panel1.add(panel4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tablaStock = new JTable();
        tablaStock.setAlignmentX(0.5f);
        tablaStock.setBackground(new Color(-14865084));
        tablaStock.setFillsViewportHeight(true);
        Font tablaStockFont = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 16, tablaStock.getFont());
        if (tablaStockFont != null) tablaStock.setFont(tablaStockFont);
        tablaStock.setForeground(new Color(-988200));
        tablaStock.setGridColor(new Color(-3356196));
        tablaStock.setIntercellSpacing(new Dimension(1, 1));
        tablaStock.setPreferredScrollableViewportSize(new Dimension(-1, -1));
        tablaStock.setRowHeight(25);
        tablaStock.setRowMargin(1);
        tablaStock.setSelectionBackground(new Color(-15920351));
        tablaStock.setSelectionForeground(new Color(-988200));
        tablaStock.setShowHorizontalLines(true);
        tablaStock.setShowVerticalLines(true);
        tablaStock.putClientProperty("html.disable", Boolean.FALSE);
        panel4.add(tablaStock, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


}
